CREATE TABLE country(
   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR NOT NULL CHECK (name <> ''),
   flag VARCHAR NOT NULL,
   region VARCHAR NOT NULL CHECK (region <> ''),
   capital VARCHAR NOT NULL CHECK (capital <> ''),
   subregion VARCHAR,
   area INTEGER,
   population INTEGER,
);
CREATE TABLE tourist_activity(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR NOT NULL CHECK (name <> ''),
  difficulty INTEGER,
  duracion VARCHAR,
  season VARCHAR
);
  ('verano','otoño','invierno','primavera')